services:
  postgres:
    image: postgres:16
    container_name: hr-postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hr
    ports: ["5432:5432"]

  mongo:
    image: mongo:7
    container_name: hr-mongo
    ports: ["27017:27017"]

  neo4j:
    image: neo4j:5
    container_name: hr-neo4j
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"